import test from 'node:test';
import assert from 'node:assert/strict';
import { readdirSync, readFileSync } from 'node:fs';

import en from '../src/locales/en.js';
import ptBR from '../src/locales/pt-BR.js';
import { getCatalogue, msg, setCatalogue } from '../src/core/messages.js';
import { decodeText } from '../src/core/base64.js';
import { jsonToJava } from '../src/core/json-to-java.js';

const LOCALES = { en, 'pt-BR': ptBR };
const placeholders = (text) => [...String(text).matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort();

test.afterEach(() => setCatalogue(en)); // não vazar idioma entre os testes

test('os catálogos têm exatamente as mesmas chaves', () => {
  const enKeys = Object.keys(en).sort();
  const ptKeys = Object.keys(ptBR).sort();

  const missingInPt = enKeys.filter((key) => !(key in ptBR));
  const missingInEn = ptKeys.filter((key) => !(key in en));

  assert.deepEqual(missingInPt, [], 'chaves presentes em en e ausentes em pt-BR');
  assert.deepEqual(missingInEn, [], 'chaves presentes em pt-BR e ausentes em en');
});

test('os placeholders batem entre os idiomas', () => {
  const mismatches = Object.keys(en)
    .filter((key) => placeholders(en[key]).join() !== placeholders(ptBR[key]).join())
    .map((key) => `${key}: en=[${placeholders(en[key])}] pt=[${placeholders(ptBR[key])}]`);

  assert.deepEqual(mismatches, [], 'placeholders divergentes');
});

test('nenhuma tradução ficou vazia ou igual ao nome da chave', () => {
  for (const [language, catalogue] of Object.entries(LOCALES)) {
    for (const [key, value] of Object.entries(catalogue)) {
      assert.ok(String(value).trim().length > 0, `${language}: "${key}" está vazia`);
      assert.notEqual(value, key, `${language}: "${key}" não foi traduzida`);
    }
  }
});

test('todo código usado no núcleo existe no catálogo', () => {
  const used = new Set();
  for (const file of readdirSync('src/core')) {
    if (!file.endsWith('.js')) continue;
    const source = readFileSync(`src/core/${file}`, 'utf8');
    for (const match of source.matchAll(/'(core\.[\w.]+)'/g)) used.add(match[1]);
  }

  assert.ok(used.size > 20, 'o scan deveria encontrar dezenas de códigos');
  const unknown = [...used].filter((code) => !(code in en));
  assert.deepEqual(unknown, [], 'códigos usados no core que não existem no catálogo');
});

test('interpolação substitui apenas os parâmetros informados', () => {
  assert.equal(
    msg('core.base64.invalidChar', { char: '#', position: 5 }),
    'Invalid Base64 character: "#" at position 5.',
  );
  // Placeholder sem valor permanece literal, o que torna o esquecimento visível.
  assert.match(msg('core.base64.invalidChar', { char: '#' }), /\{position\}/);
});

test('código desconhecido volta como a própria chave', () => {
  assert.equal(msg('core.inexistente.xyz'), 'core.inexistente.xyz');
});

test('trocar o catálogo muda erros, avisos e código gerado', () => {
  const sample = JSON.stringify({ vazio: [] });

  setCatalogue(en);
  assert.match(jsonToJava(sample).output, /^\/\/ Generated by Codec Studio/);
  assert.match(jsonToJava(sample).warnings[0], /is empty/);
  assert.match(decodeText('Zm9v YmFy').warnings[0], /ignored/);

  setCatalogue(ptBR);
  assert.match(jsonToJava(sample).output, /^\/\/ Gerado pelo Codec Studio/);
  assert.match(jsonToJava(sample).warnings[0], /está vazio/);
  assert.match(decodeText('Zm9v YmFy').warnings[0], /ignorad/);
});

test('o código do erro não muda com o idioma', () => {
  const codeIn = (catalogue) => {
    setCatalogue(catalogue);
    try {
      decodeText('Zm9v#YmFy');
    } catch (error) {
      return { code: error.code, message: error.message };
    }
    throw new Error('esperava uma exceção');
  };

  const english = codeIn(en);
  const portuguese = codeIn(ptBR);

  assert.equal(english.code, portuguese.code, 'o código é estável');
  assert.notEqual(english.message, portuguese.message, 'a mensagem é traduzida');
});

test('catálogo inválido volta para o inglês', () => {
  setCatalogue(null);
  assert.equal(getCatalogue(), en);
});

test('_locales do manifesto tem as mesmas chaves nos dois idiomas', () => {
  const read = (dir) => JSON.parse(readFileSync(`_locales/${dir}/messages.json`, 'utf8'));
  const enManifest = read('en');
  const ptManifest = read('pt_BR');

  assert.deepEqual(Object.keys(enManifest).sort(), Object.keys(ptManifest).sort());
  for (const [key, entry] of Object.entries(enManifest)) {
    assert.ok(entry.message, `en: ${key} sem message`);
    assert.ok(ptManifest[key].message, `pt_BR: ${key} sem message`);
  }
  // A loja corta a descrição em 132 caracteres.
  for (const [language, catalogue] of [['en', enManifest], ['pt_BR', ptManifest]]) {
    assert.ok(
      catalogue.extDescription.message.length <= 132,
      `${language}: descrição com ${catalogue.extDescription.message.length} caracteres (máx. 132)`,
    );
  }
});

test('todo __MSG_*__ do manifesto existe nos _locales', () => {
  const manifest = readFileSync('manifest.json', 'utf8');
  const messages = JSON.parse(readFileSync('_locales/en/messages.json', 'utf8'));
  const used = [...manifest.matchAll(/__MSG_(\w+)__/g)].map((match) => match[1]);

  assert.ok(used.length >= 4, 'o manifesto deveria referenciar várias mensagens');
  for (const key of used) {
    assert.ok(key in messages, `__MSG_${key}__ não existe em _locales/en/messages.json`);
  }
});
