/**
 * English catalogue — also the fallback used by the core when no other locale is
 * installed, which keeps `src/core/` usable (and testable) on its own.
 *
 * Placeholders use {braces}. Keys are flat and prefixed by area:
 *   core.*  messages thrown or reported by the conversion engine
 *   ui.*    everything rendered by the interface
 */

export default {
  /* ------------------------------------------------------------- core/base64 */
  'core.base64.invalidChar': 'Invalid Base64 character: "{char}" at position {position}.',
  'core.base64.invalidChar.hint':
    'The Base64 alphabet accepts A–Z, a–z, 0–9, "+" and "/" (or "-" and "_" in URL-safe mode).',
  'core.base64.dataAfterPadding': 'Data found after the "=" padding at position {position}.',
  'core.base64.dataAfterPadding.hint': 'The "=" character may only appear at the end of the string.',
  'core.base64.whitespaceStrict': 'Spaces and line breaks are not allowed in strict mode.',
  'core.base64.whitespaceIgnored': 'Spaces and line breaks were ignored.',
  'core.base64.mixedAlphabetStrict': 'The input mixes the standard ("+/") and URL-safe ("-_") alphabets.',
  'core.base64.mixedAlphabet': 'The input mixes the standard and URL-safe alphabets; both were accepted.',
  'core.base64.invalidPadding': 'Invalid padding: {count} "=" characters at the end.',
  'core.base64.invalidPadding.hint': 'Base64 allows at most two "=".',
  'core.base64.invalidLength': 'Invalid length: a single leftover Base64 character at the end.',
  'core.base64.invalidLength.hint':
    'A valid Base64 string has a length that is a multiple of 4 (padding aside).',
  'core.base64.missingPaddingStrict': 'Missing "=" padding in strict mode.',
  'core.base64.missingPadding': 'Missing "=" padding; the input was decoded anyway.',
  'core.base64.oddPadding': 'The trailing "=" count does not complete a 4-character block.',
  'core.base64.notUtf8': 'The decoded bytes are not valid UTF-8 — this is most likely binary content.',

  /* --------------------------------------------------------------- core/json */
  'core.json.empty': 'Nothing to convert.',
  'core.json.empty.hint': 'Paste or type some JSON in the input panel.',
  'core.json.invalidAt': 'Invalid JSON at line {line}, column {column}.',
  'core.json.invalid': 'Invalid JSON.',
  'core.json.hint': '{message} — near: {excerpt}',
  'core.json.scan.extraContent': 'Extra content after the end of the document ("{char}").',
  'core.json.scan.unexpectedEnd': 'The document ended sooner than expected.',
  'core.json.scan.unexpectedValue': 'Unexpected value starting with "{char}".',
  'core.json.scan.expectedKey': 'Expected a key name in double quotes.',
  'core.json.scan.expectedColon': 'Expected ":" after the key name.',
  'core.json.scan.trailingCommaObject': 'Trailing comma before "}".',
  'core.json.scan.trailingCommaArray': 'Trailing comma before "]".',
  'core.json.scan.unclosedObject': 'The object was never closed with "}".',
  'core.json.scan.expectedCommaOrBrace': 'Expected "," or "}" but found "{char}".',
  'core.json.scan.unclosedArray': 'The array was never closed with "]".',
  'core.json.scan.expectedCommaOrBracket': 'Expected "," or "]" but found "{char}".',
  'core.json.scan.newlineInString': 'Line break inside a string (use \\n).',
  'core.json.scan.unclosedString': 'String is missing its closing quote.',
  'core.json.scan.badNumber': 'Malformed number.',

  /* -------------------------------------------------------- core/json → java */
  'core.jsonToJava.header': '// Generated by Codec Studio — review before shipping to production.',
  'core.jsonToJava.rootArrayNote': '// The JSON root is an array — deserialize it as {type}.',
  'core.jsonToJava.mixedTypes': 'Field "{name}" mixes types ({types}); it was generated as Object.',
  'core.jsonToJava.rootMustBeObject': 'The JSON must be an object or an array to become Java classes.',
  'core.jsonToJava.rootMustBeObject.hint': 'Got {type} instead. Wrap the content in { } to generate a class.',
  'core.jsonToJava.rootIsArrayOfScalars': 'The root is an array of plain values: use {type} directly.',
  'core.jsonToJava.emptyArray': 'The array "{name}" is empty, so the element type became Object.',
  'core.jsonToJava.dynamicKeys': '"{name}" has dynamic keys, so it was generated as Map<String, …>.',
  'core.jsonToJava.emptyObject': 'The object "{name}" is empty, so class {className} has no fields.',

  /* -------------------------------------------------------- core/java → json */
  'core.javaToJson.empty': 'Nothing to convert.',
  'core.javaToJson.empty.hint': 'Paste a Java class or record in the input panel.',
  'core.javaToJson.noTypes': 'No class, record or enum found.',
  'core.javaToJson.noTypes.hint':
    'Paste the full declaration, including "class Name { … }" or "record Name(…) { }".',
  'core.javaToJson.interfaceNoFields': '"{name}" is an interface with no fields, so the object is empty.',
  'core.javaToJson.cyclic': 'Cyclic reference in "{name}"; the recursive field became null.',
  'core.javaToJson.noFields': '"{name}" has no instance fields, so the object is empty.',
  'core.javaToJson.unknownType': 'Type "{name}" is unknown, so it was generated as an empty object.',

  /* ------------------------------------------- core: sample values (java→json) */
  'core.convert.unknownFormat': 'Unknown format: {name}.',
  'core.convert.unknownFormat.hint': 'Pick one of the formats listed in the selector.',

  /* --------------------------------------------- core: linguagens (genérico) */
  'core.lang.header': '// Generated by Codec Studio — review before shipping to production.',
  'core.lang.rootArrayNote': '// The document root is a collection — deserialize it as {type}.',
  'core.lang.empty': 'Nothing to convert.',
  'core.lang.empty.hint': 'Paste some {lang} code in the input panel.',
  'core.lang.noTypes': 'No {lang} type declaration was found.',
  'core.lang.noTypes.hint': 'Paste the full declaration, including the type name and its body.',
  'core.lang.unknownType': 'Type "{name}" is not known to the {lang} reader; it became a free-form value.',
  'core.lang.rootMustBeObject': '{lang} needs an object to describe.',
  'core.lang.rootMustBeObject.hint': 'The document is a {type}, which has no fields to turn into a {lang} type. Wrap it in an object.',

  /* ---------------------------------------------- core: dados (JSON e YAML) */
  'core.data.rootIsArrayOfScalars': 'The root is an array of plain values, so no type was declared.',
  'core.data.rootIsScalar': 'The document root is a single {type} value, so there is no structure to model.',
  'core.data.mixedTypes': 'Field "{name}" mixes types ({types}); it became a free-form value.',
  'core.data.emptyArray': 'The array "{name}" is empty, so the element type is unknown.',
  'core.data.dynamicKeys': '"{name}" has dynamic keys, so it became a dictionary.',
  'core.data.emptyObject': 'The object "{name}" is empty, so type {className} has no fields.',
  'core.data.cyclic': 'Cyclic reference in "{name}"; the recursive field became null.',
  'core.data.noFields': '"{name}" has no fields, so the object came out empty.',

  /* --------------------------------------------------------------- core/yaml */
  'core.yaml.empty': 'Nothing to convert.',
  'core.yaml.empty.hint': 'Paste or type some YAML in the input panel.',
  'core.yaml.unsupported': 'This YAML uses anchors, aliases or merge keys.',
  'core.yaml.unsupported.hint': 'Those build a reference graph that this converter does not resolve. Expand them and try again.',
  'core.yaml.badIndent': 'Unexpected indentation on line {line}.',
  'core.yaml.badIndent.hint': 'Nested blocks must line up consistently; mixing tabs and spaces also breaks the structure.',
  'core.yaml.expectedKey': 'Line {line} is neither a "key: value" pair nor a "- item".',
  'core.yaml.expectedKey.hint': 'Inside a mapping every line needs a key followed by a colon.',

  'core.sample.mapKey': 'key',
  'core.sample.text': 'text',
  'core.sample.name': 'Jane Doe',
  'core.sample.email': 'person@example.com',
  'core.sample.url': 'https://example.com/resource',
  'core.sample.phone': '+1 555 010 0000',
  'core.sample.city': 'San Francisco',
  'core.sample.state': 'CA',
  'core.sample.country': 'US',
  'core.sample.zip': '94105',
  'core.sample.status': 'ACTIVE',
  'core.sample.description': 'Sample description',
  'core.sample.title': 'Sample title',
  'core.sample.locale': 'en-US',
  'core.sample.currency': 'USD',
  'core.sample.masked': '••••••••',

  /* ---------------------------------------------------------------- ui/chrome */
  'ui.brand.tagline': '100% offline · no permissions',
  'ui.tab.base64': 'Base64',
  'ui.tab.jsonJava': 'JSON ⇄ Java',
  'ui.tabs.label': 'Tool',
  'ui.action.theme': 'Toggle light/dark theme',
  'ui.action.expand': 'Open in a tab',
  'ui.action.language': 'Mudar para português',
  'ui.action.languageCode': 'EN',
  'ui.options.label': 'Conversion options',

  'ui.panel.input': 'Input',
  'ui.panel.output': 'Output',
  'ui.panel.sample': 'Example',
  'ui.panel.clear': 'Clear',
  'ui.panel.download': 'Download',
  'ui.panel.copy': 'Copy',
  'ui.panel.copied': 'Copied',
  'ui.convert': 'Convert',
  'ui.convert.title': 'Convert (Ctrl/⌘ + Enter)',
  'ui.swap': 'Swap direction',
  'ui.swap.title': 'Swap direction (Ctrl/⌘ + I)',
  'ui.dropzone': 'Drop the file to load it',
  'ui.placeholder.output': 'The result shows up here.',
  'ui.input.placeholder': 'Type, paste or drop a file here…',
  'ui.status.shield': 'Nothing leaves your browser',
  'ui.status.convert': 'convert',
  'ui.status.swap': 'swap',
  'ui.status.copy': 'copy',
  'ui.footer.copyright': '© 2026 Rafael WMS',

  /* --------------------------------------------------------------- ui/metrics */
  'ui.unit.char.one': 'character',
  'ui.unit.char.other': 'characters',
  'ui.unit.byte.one': 'byte',
  'ui.unit.byte.other': 'bytes',
  'ui.unit.line.one': 'line',
  'ui.unit.line.other': 'lines',
  'ui.metrics.none': '—',
  'ui.metrics.ms': '{value} ms',
  'ui.metrics.largeInput': 'large input — use the Convert button',

  /* ---------------------------------------------------------------- ui/errors */
  'ui.error.generic': 'Could not convert.',
  'ui.toast.copied': 'Result copied.',
  'ui.toast.nothingToCopy': 'Nothing to copy yet.',
  'ui.toast.copyBlocked': 'The browser blocked the copy.',
  'ui.toast.nothingToDownload': 'Nothing to download yet.',
  'ui.toast.downloaded': 'Saved {name}.',
  'ui.toast.fileLoaded': '{name} loaded.',
  'ui.toast.fileTooLarge': 'File is too large (max {size} MB).',
  'ui.toast.fileError': 'Could not read the file.',
  'ui.download.encoded': 'encoded.b64.txt',
  'ui.download.decoded': 'decoded.txt',

  /* ---------------------------------------------------------------- ui/labels */
  'ui.label.detected': '{output} · detected',
  'ui.label.base64.encode.input': 'Text',
  'ui.label.base64.encode.output': 'Base64',
  'ui.label.base64.encode.placeholder': 'Type the text you want encoded as Base64…',
  'ui.label.base64.decode.input': 'Base64',
  'ui.label.base64.decode.output': 'Text',
  'ui.label.base64.decode.placeholder': 'Paste the Base64 you want decoded…',
  'ui.label.base64.auto.input': 'Text or Base64',
  'ui.label.base64.auto.output': 'Result',
  'ui.label.base64.auto.placeholder': 'Paste either one — the direction is detected…',
  'ui.label.jsonJava.json-to-java.input': 'JSON',
  'ui.label.jsonJava.json-to-java.output': 'Java',
  'ui.label.jsonJava.json-to-java.placeholder': '{\n  "id": 1,\n  "name": "Jane"\n}',
  'ui.label.jsonJava.java-to-json.input': 'Java',
  'ui.label.jsonJava.java-to-json.output': 'JSON',
  'ui.label.jsonJava.java-to-json.placeholder': 'public record Person(Long id, String name) { }',

  /* --------------------------------------------------------------- ui/options */
  'ui.opt.direction': 'Direction',
  'ui.opt.encode': 'Encode',
  'ui.opt.decode': 'Decode',
  'ui.opt.auto': 'Auto',
  'ui.opt.alphabet': 'Alphabet',
  'ui.opt.standard': 'Standard',
  'ui.opt.urlSafe': 'URL-safe',
  'ui.opt.padding': 'Padding =',
  'ui.opt.wrap': 'Wrap at 76',
  'ui.opt.strict': 'Strict mode',
  'ui.opt.jsonToJava': 'JSON → Java',
  'ui.opt.javaToJson': 'Java → JSON',
  'ui.opt.style': 'Style',
  'ui.opt.record': 'Record',
  'ui.opt.pojo': 'POJO',
  'ui.opt.lombok': 'Lombok',
  'ui.opt.className': 'Class',
  'ui.opt.classNamePlaceholder': 'Root',
  'ui.opt.package': 'Package',
  'ui.opt.packagePlaceholder': 'com.example',
  'ui.opt.jackson': 'Jackson',
  'ui.opt.jacksonAll': 'Annotate all',
  'ui.opt.primitives': 'Primitives',
  'ui.opt.detectDates': 'Detect dates',
  'ui.opt.separateFiles': 'Separate files',
  'ui.opt.values': 'Values',
  'ui.opt.example': 'Example',
  'ui.opt.empty': 'Empty',
  'ui.opt.rootType': 'Root',

  /* ------------------------------------------------------- ui: formatos novos */
  'ui.surface.text': 'Plain text',
  'ui.surface.base64': 'Base64',
  'ui.format.from': 'Convert from',
  'ui.format.to': 'Convert to',
  'ui.options.title': 'Options',
  'ui.options.close': 'Close options',
  'ui.options.reset': 'Reset',
  'ui.options.none': 'This pair has no options to adjust.',
  'ui.toast.optionsReset': 'Options restored to the defaults.',
  'ui.toast.cannotSwap': 'These two formats cannot swap places.',

  'ui.opt.namespace': 'Namespace',
  'ui.opt.namespacePlaceholder': 'Company.Api',
  'ui.opt.goPackagePlaceholder': 'main',
  'ui.opt.class': 'Class',
  'ui.opt.struct': 'Struct',
  'ui.opt.interface': 'Interface',
  'ui.opt.typeAlias': 'Type',
  'ui.opt.angular': 'Angular',
  'ui.opt.jsonAttributes': 'JSON attributes',
  'ui.opt.jsonAttributesAll': 'Annotate all',
  'ui.opt.nullable': 'Nullable types',
  'ui.opt.exportTypes': 'export',
  'ui.opt.optionalMarker': 'Use "?" for optional',
  'ui.opt.readonly': 'readonly fields',
  'ui.opt.useDate': 'Date instead of string',
  'ui.opt.finalFields': 'final fields',
  'ui.opt.jsonMethods': 'fromJson / toJson',
  'ui.opt.namedParameters': 'Named parameters',
  'ui.opt.codable': 'Codable',
  'ui.opt.letConstants': 'let instead of var',
  'ui.opt.codingKeys': 'CodingKeys',
  'ui.opt.jsonTags': 'JSON tags',
  'ui.opt.omitempty': 'omitempty',
  'ui.opt.pointerOptionals': 'Pointer for optional',
  'ui.opt.useTime': 'time.Time for dates',

  'ui.sample.text': 'Hello, world! Codec Studio runs 100% offline. 🔒',
  'ui.sample.base64': 'SGVsbG8sIHdvcmxkISBDb2RlYyBTdHVkaW8gcnVucyAxMDAlIG9mZmxpbmUuIPCflJI=',
  'ui.sample.yaml': `id: 1024
full_name: Jane Souza
email: jane@example.com
active: true
score: 9.75
created_at: 2026-07-30T10:15:30Z
address:
  city: San Francisco
  state: CA
  zip: "94105"
orders:
  - sku: CS-100
    quantity: 2
    total: 199.9
tags:
  - premium
  - beta`,
  'ui.sample.csharp': `public class Order
{
    public long Id { get; set; }

    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; }

    public decimal Total { get; set; }
    public string? Note { get; set; }
    public List<Item> Items { get; set; }
}

public class Item
{
    public string Sku { get; set; }
    public int Quantity { get; set; }
}`,
  'ui.sample.typescript': `export interface Order {
  id: number;
  created_at: string;
  total: number;
  note?: string;
  status: 'open' | 'paid' | 'cancelled';
  items: Item[];
}

export interface Item {
  sku: string;
  quantity: number;
}`,
  'ui.sample.dart': `class Order {
  final int id;
  final DateTime createdAt;
  final double total;
  final String? note;
  final List<Item> items;

  Order({
    required this.id,
    required this.createdAt,
    required this.total,
    this.note,
    required this.items,
  });
}

class Item {
  final String sku;
  final int quantity;

  Item({required this.sku, required this.quantity});
}`,
  'ui.sample.swift': `struct Order: Codable {
    let id: Int
    let createdAt: Date
    let total: Double
    let note: String?
    let items: [Item]

    enum CodingKeys: String, CodingKey {
        case id
        case createdAt = "created_at"
        case total
        case note
        case items
    }
}

struct Item: Codable {
    let sku: String
    let quantity: Int
}`,
  'ui.sample.go': `type Order struct {
	ID        int64     \`json:"id"\`
	CreatedAt time.Time \`json:"created_at"\`
	Total     float64   \`json:"total"\`
	Note      *string   \`json:"note,omitempty"\`
	Items     []Item    \`json:"items"\`
}

type Item struct {
	SKU      string \`json:"sku"\`
	Quantity int    \`json:"quantity"\`
}`,

  /* -------------------------------------------------------- ui/sample content */
  'ui.sample.json': `{
  "id": 1024,
  "full_name": "Jane Souza",
  "email": "jane@example.com",
  "active": true,
  "score": 9.75,
  "created_at": "2026-07-30T10:15:30Z",
  "address": {
    "city": "San Francisco",
    "state": "CA",
    "zip": "94105"
  },
  "orders": [
    {
      "sku": "CS-100",
      "quantity": 2,
      "total": 199.9
    },
    {
      "sku": "CS-200",
      "quantity": 1,
      "total": 49.9,
      "note": "gift"
    }
  ],
  "tags": [
    "premium",
    "beta"
  ]
}`,
  'ui.sample.java': `public class Order {
    private Long id;
    private String customer;

    @JsonProperty("created_at")
    private OffsetDateTime createdAt;

    private BigDecimal total;
    private Status status;
    private List<Item> items;

    public static class Item {
        private String sku;
        private int quantity;
        private BigDecimal price;
    }
}

enum Status { OPEN, PAID, CANCELLED }`,
};
